#!/usr/bin/env bash
# cont-init 02 — (re)generate /opt/data/config.yaml and /opt/data/.env
# from the Space Variables/Secrets at EVERY boot, so changing a variable
# in Space settings + Restart is enough to reconfigure everything.
set -u

H=/opt/data
mkdir -p "$H"

# ------------------------------------------------ config.yaml
MODEL_ID="${HERMES_MODEL:-SET-HERMES-MODEL-VARIABLE}"
WEB_BACKEND="${HERMES_WEB_BACKEND:-tavily}"

cat > "$H/config.yaml" <<EOF
# ==== auto-generated by HF kit (rebuilt at every boot) ====
model:
  provider: ninerouter
  default: "${MODEL_ID}"

providers:
  # 9Router — free/paid models you connect in its dashboard (Kiro, OpenCode Free, ...)
  ninerouter:
    api: http://127.0.0.1:20128/v1
    key_env: NINEROUTER_API_KEY
    transport: chat_completions
    discover_models: true

  # OmniRouter — keyless web models (Qwen / Gemini / OpenCode guest)
  omnirouter:
    api: http://127.0.0.1:8080/v1
    key_env: OMNI_ROUTER_KEY
    transport: chat_completions
    discover_models: true

web:
  backend: ${WEB_BACKEND}
  keyless_fallback: true
  keyless_rescue: true
EOF

# ------------------------------------------------ .env
DASH=0
if [ -n "${DASHBOARD_USERNAME:-}" ] && [ -n "${DASHBOARD_PASSWORD:-}" ]; then
    DASH=1
fi

# stable session secret for the dashboard (persists in /opt/data)
if [ ! -f "$H/.dash_secret" ]; then
    tr -dc 'a-f0-9' < /dev/urandom | head -c 64 > "$H/.dash_secret"
fi
DASH_SECRET="$(cat "$H/.dash_secret")"

{
  echo "# ==== auto-generated by HF kit (rebuilt at every boot) ===="
  if [ -n "${TELEGRAM_BOT_TOKEN:-}" ]; then
    echo "TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}"
  fi
  if [ -n "${TELEGRAM_ALLOWED_USERS:-}" ]; then
    echo "TELEGRAM_ALLOWED_USERS=${TELEGRAM_ALLOWED_USERS}"
  fi
  echo "HERMES_TIMEZONE=${HERMES_TIMEZONE:-Asia/Tehran}"

  # ---- web-to-api: OpenAI-compatible API server on 8642 ----
  if [ -n "${HERMES_API_KEY:-}" ]; then
    echo "API_SERVER_ENABLED=true"
    echo "API_SERVER_KEY=${HERMES_API_KEY}"
    echo "API_SERVER_HOST=127.0.0.1"
    echo "API_SERVER_PORT=8642"
  else
    echo "API_SERVER_ENABLED=false"
  fi

  # ---- web dashboard on 9119 (behind Caddy at /hermes/) ----
  if [ "$DASH" = "1" ]; then
    echo "HERMES_DASHBOARD=1"
    echo "HERMES_DASHBOARD_PORT=9119"
    echo "HERMES_DASHBOARD_HOST=127.0.0.1"
    echo "HERMES_DASHBOARD_BASIC_AUTH_USERNAME=${DASHBOARD_USERNAME}"
    echo "HERMES_DASHBOARD_BASIC_AUTH_PASSWORD=${DASHBOARD_PASSWORD}"
    echo "HERMES_DASHBOARD_BASIC_AUTH_SECRET=${DASH_SECRET}"
    echo "HERMES_DASHBOARD_PUBLIC_URL=https://${SPACE_HOST:-localhost}/hermes/"
  else
    echo "HERMES_DASHBOARD=0"
  fi

  # ---- provider keys for config.yaml providers ----
  if [ -n "${NINEROUTER_API_KEY:-}" ]; then
    echo "NINEROUTER_API_KEY=${NINEROUTER_API_KEY}"
  fi
  if [ -n "${OMNI_ROUTER_KEY:-}" ]; then
    echo "OMNI_ROUTER_KEY=${OMNI_ROUTER_KEY}"
  fi
} > "$H/.env"

echo "[write-config] config.yaml + .env written (model=${MODEL_ID}, dashboard=${DASH})."
exit 0
